# Generated by Django 5.2.12 on 2026-04-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteFinderWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_stop_mins',
            field=models.IntegerField(default=15, help_text='Default minutes spent at each individual garage sale.'),
        ),
    ]
