# Generated by Django 5.2.13 on 2026-04-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteFinderWeb', '0003_savedroute_routestop_addressrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressrating',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='addressrating',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='arrival_time',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='departure_time',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='drive_time_str',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='name',
            field=models.TextField(default='Weekend Route'),
        ),
        migrations.AlterField(
            model_name='savedroute',
            name='start_time_str',
            field=models.TextField(default='08:00'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='home_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
