# Generated by Django 5.2.13 on 2026-04-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteFinderWeb', '0004_alter_addressrating_address_alter_addressrating_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressrating',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
