# Generated by Django 5.2.13 on 2026-04-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteFinderWeb', '0005_addressrating_is_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='home_address',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_street',
            field=models.TextField(blank=True, help_text='Street address and City'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
