# Generated by Django 5.2.13 on 2026-04-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteFinderWeb', '0006_remove_userprofile_home_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='looking_for',
            field=models.TextField(blank=True, help_text="Comma-separated items you are looking for (e.g. 'Vintage Pyrex, Gameboy')"),
        ),
    ]
