# Generated by Django 5.2.13 on 2026-04-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteFinderWeb', '0007_userprofile_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressrating',
            name='address',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='address',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
