# Generated by Django 6.0.4 on 2026-06-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteFinderWeb', '0009_scoutintel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Toggle all AI functionalities in the application'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_thinking_effort',
            field=models.IntegerField(default=50, help_text='Adjust thinking effort (1-100)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_thinking_enabled',
            field=models.BooleanField(default=False, help_text='Toggle AI thinking/reasoning'),
        ),
    ]
