# Generated by Django 6.0.4 on 2026-06-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RouteFinderWeb', '0010_userprofile_ai_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='Optional API Key for authentication', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_api_url',
            field=models.CharField(blank=True, help_text='Custom API base URL', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_model',
            field=models.CharField(default='gemma:4b', help_text='Model name to target', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_provider',
            field=models.CharField(choices=[('ollama', 'Ollama (Native)'), ('openai', 'OpenAI Compatible')], default='ollama', max_length=50),
        ),
    ]
